import { describe,it,expect } from 'vitest';
import { buildExamCalendar, parseExamCalendar } from './examCalendar';
import { localDateKey, mergeExams, type ExamRecord } from './exams';
const wrap=(events:string[])=>['BEGIN:VCALENDAR','VERSION:2.0',...events,'END:VCALENDAR',''].join('\r\n');
const event=(fields:string[])=>['BEGIN:VEVENT',...fields,'END:VEVENT'].join('\r\n');
const fields=['UID:test@example.test','SUMMARY:考试','DTSTART:20261225T090000','DTEND:20261225T110000'];
describe('one-off exam ICS import/export',()=>{
  it('imports an exact one-off date without requiring an academic week',()=>{const parsed=parseExamCalendar(wrap([event(fields)]));expect(parsed.exams[0]).toMatchObject({title:'考试',date:'2026-12-25',startTime:'09:00',endTime:'11:00',reminderMinutes:[]});expect(parsed.skipped).toBe(0);});
  it('uses stable ids and does not overwrite existing exams on reimport',()=>{const text=wrap([event(fields)]),original=parseExamCalendar(text).exams;expect(mergeExams(original,parseExamCalendar(text).exams)).toEqual(original);});
  it('converts explicit UTC and China timezone into the same instant',()=>{const china=parseExamCalendar(wrap([event(fields.map(value=>value.replace('DTSTART:','DTSTART;TZID=Asia/Shanghai:').replace('DTEND:','DTEND;TZID=Asia/Shanghai:')))])).exams;const utc=parseExamCalendar(wrap([event(['SUMMARY:考试','DTSTART:20261225T010000Z','DTEND:20261225T030000Z'])])).exams;expect(china[0].date).toBe(localDateKey(new Date('2026-12-25T01:00:00Z')));expect(china[0].startTime).toBe(utc[0].startTime);});
  it('skips unknown timezones instead of shifting the date silently',()=>{const parsed=parseExamCalendar(wrap([event(fields.map(value=>value.replace('DTSTART:','DTSTART;TZID=Mars/Test:')))]));expect(parsed.exams).toHaveLength(0);expect(parsed.warnings[0]).toContain('时区');});
  it('reports invalid dates, all-day, missing end, recurrence and cancelled events',()=>{const entries=[fields.map(value=>value.replace('20261225','20260229')),['SUMMARY:全天','DTSTART;VALUE=DATE:20261225','DTEND;VALUE=DATE:20261226'],fields.filter(value=>!value.startsWith('DTEND')), [...fields,'RRULE:FREQ=WEEKLY'],[...fields,'STATUS:CANCELLED']];const parsed=parseExamCalendar(wrap(entries.map(event)));expect(parsed.skipped).toBe(5);expect(parsed.exams).toEqual([]);expect(parsed.warnings).toHaveLength(5);});
  it('rejects reversed times, cross-day times and nonzero seconds',()=>{for(const end of ['20261225T080000','20261226T100000','20261225T110030'])expect(parseExamCalendar(wrap([event(fields.map(value=>value.startsWith('DTEND:')?`DTEND:${end}`:value))])).exams).toHaveLength(0);});
  it('preserves line folding, escaping, seat, notes and reminders on a round trip',()=>{const exam:ExamRecord={id:'exam-你好',title:'大学英语,期末;考试\\测试',date:'2026-12-25',startTime:'09:00',endTime:'11:00',location:'教学楼 A301',seat:'18',note:'中文内容😀'.repeat(50)+'\n带学生证',reminderMinutes:[1440,30]};const text=buildExamCalendar([exam]);expect(text).toContain('TRIGGER:-PT1440M');expect(text).toContain('\r\n ');expect(text.split('\r\n').every(line=>new TextEncoder().encode(line).length<=75)).toBe(true);expect(parseExamCalendar(text).exams).toEqual([exam]);});
  it('ignores third-party VALARM times and does not confuse them with the exam',()=>{const parsed=parseExamCalendar(wrap([event([...fields,'BEGIN:VALARM','ACTION:DISPLAY','TRIGGER;VALUE=DATE-TIME:20261224T090000Z','DESCRIPTION:外部提醒','END:VALARM'])]));expect(parsed.exams[0].startTime).toBe('09:00');expect(parsed.exams[0].reminderMinutes).toEqual([]);});
  it('reports duplicate ids and ambiguous fields, but retains valid events',()=>{const parsed=parseExamCalendar(wrap([event(fields),event(fields),event([...fields,'DTSTART:20261225T100000'])]));expect(parsed.exams).toHaveLength(1);expect(parsed.skipped).toBe(2);});
  it('rejects truncated or oversized files without a partial import',()=>{expect(()=>parseExamCalendar(wrap([event(fields)]).replace('END:VCALENDAR',''))).toThrow();expect(()=>parseExamCalendar('x'.repeat(4*1024*1024+1))).toThrow('4 MB');expect(()=>buildExamCalendar([])).toThrow();});
});
